user:
    pattern:  /
    defaults: { _controller: "RoleVotersBlogBundle:User:index" }

user_show:
    pattern:  /show/{id}
    defaults: { _controller: "RoleVotersBlogBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "RoleVotersBlogBundle:User:new" }

user_create_account:
    pattern:  /create-account
    defaults: { _controller: "RoleVotersBlogBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "RoleVotersBlogBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "RoleVotersBlogBundle:User:edit" }

user_update:
    pattern:  /update/{id}
    defaults: { _controller: "RoleVotersBlogBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "RoleVotersBlogBundle:User:delete" }
