security:
    encoders:
        RoleVoters\BlogBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: RoleVotersBlogBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/show$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/$, roles: ROLE_USER }
        - { path: ^/profile$, roles: ROLE_USER }
