parameters:


services:
    object_voter:
        class: RoleVoters\BlogBundle\Securtiy\ObjectVoter
        public: false
        arguments: ["%customRoles%"]
        tags:
            - { name: security.voter, priority: 100 }